[package]
name = "rss-reader-rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# db
rusqlite = {version="0.31.0", features = ["chrono"]}
# date
chrono = "0.4.10"
# web
axum = "0.7.5"
tokio = { version = "1.37.0", features = ["full"] }
tower = "0.4.13"
serde_json = { version = "1.0", default-features = false, features = ["alloc"] }
askama = "0.12.1"